### ISSUE TITLE
I can't build the dll

### ISSUE THREAD

**Issue by ghost** [Sanceilaks/lemi_gmod_revolution#1]
I can't build the dll, I get an error when building it - can't open the file "freetype28.lib" (LNK1104)

Debug/x86

**Comment by Sanceilaks** [comment]
Install static freetype using vcpkg or nuget

**Comment by Sanceilaks** [comment]
Install freetype from nuget and link it with project

**Comment by csxDevr** [comment]
how can i install that? i dont understand actually

> Install freetype from nuget and link it with project

**Comment by Sanceilaks** [comment]
I fixed it. Try again.

**Comment by Sanceilaks** [comment]
Ok, i`m close this
